### ISSUE TITLE
Client Directory 구조 세팅

### ISSUE THREAD

**Issue by 2Ruk** [mollrang-dev/mollrang#3]
#### 필요 사항

1. 프레임워크 선정과 사유
2. 라이브러리 선정과 사유

**Comment by DaHoon06** [comment]
### 주 프레임워크

- [ ] Next.Js With TypeScript


### 상태 관리 라이브러리

#### 클라이언트 상태 관리

두 개 중 고민 중..

- [ ] Zustand
- [ ] Redux

#### 서버 상태 관리

- [ ] React-Query


### Css Framework Or preprocessor

- [ ] Scss


### 테스팅 라이브러리

- [ ] Jest

### UI Component Doc

- [ ] StoryBook
